### ISSUE TITLE
Request Access--SAR High School

### ISSUE THREAD

**Issue by nycowboy04** [NYCIST/nycist#1]
## Repo Request Info:

**Purpose of repo**
A short description of how you plan to use the repo (host your school or department's code, curriculum purposes, etc.)

**School / EDU Institution**
The name of your school. This is so we can create a team for you and anyone else who may need access from your school, so you all can contribute to your own repo(s)

**Public or private**
Should your repo be visible to all of Github or not?

**License**
Github offers different licensing options for your repo. NYCIST recommends the MIT license, as it's simple and permissive.

Look at https://choosealicense.com/ for help with choosing a license.

**Comment by apizz** [comment]
@nycowboy04 I'll add you as a NYCIST member and create a sarhighschool team.  

FYI, this request template is specifically for requesting a repo be created.

**Comment by apizz** [comment]
Invitation sent.  Added to nycist-members & sarhighschool teams.
